"""
Manual auxiliary (haben/sein) classification for the German verbs
where prefix+root inheritance was deliberately not trusted (see
de_conjugation_rules.py docstring -- auxiliary does not reliably
inherit through prefixation, confirmed empirically: fahren=sein but
erfahren=haben; stehen=haben but entstehen=sein).

Classified from independent semantic judgment of each verb (does it
describe intransitive motion/change-of-state, or not), then compared
against the old german-verbs-database (Wiktionary-derived, CC-BY-SA)
value as a verification check. A number of verbs were found genuinely
ambiguous (dual-paradigm verbs where the specific sense represented in
the dataset isn't fully clear from the infinitive alone, e.g.
ausbrechen "to break out/escape" vs a transitive sense) and were
deliberately left out of this table rather than guessed.
"""

CLASSIFICATIONS = {
    'erhalten': 'haben', 'bestehen': 'haben', 'verstehen': 'haben',
    'verwenden': 'haben', 'verlassen': 'haben', 'entscheiden': 'haben',
    'erkennen': 'haben', 'erfahren': 'haben', 'befinden': 'haben',
    'verbinden': 'haben', 'aufnehmen': 'haben', 'aussehen': 'haben',
    'vertreten': 'haben', 'enthalten': 'haben', 'entstehen': 'sein',
    'erscheinen': 'sein', 'betragen': 'haben', 'übernehmen': 'haben',
    'abschliessen': 'haben', 'anbieten': 'haben', 'ansehen': 'haben',
    'anfangen': 'haben', 'besitzen': 'haben', 'entsprechen': 'haben',
    'annehmen': 'haben', 'absehen': 'haben', 'behalten': 'haben',
    'ergeben': 'haben', 'verbieten': 'haben', 'beschreiben': 'haben',
    'betreffen': 'haben', 'übertragen': 'haben', 'vermeiden': 'haben',
    'betreiben': 'haben', 'beweisen': 'haben', 'einladen': 'haben',
    'auftreten': 'sein', 'ausschliessen': 'haben', 'unterscheiden': 'haben',
    'ankommen': 'sein', 'versehen': 'haben', 'vergeben': 'haben',
    'beschliessen': 'haben', 'beziehen': 'haben', 'vergleichen': 'haben',
    'angeben': 'haben', 'nachdenken': 'haben', 'verbringen': 'haben',
    'unterhalten': 'haben', 'aussprechen': 'haben', 'erheben': 'haben',
    'versprechen': 'haben', 'ausgehen': 'sein', 'umgehen': 'haben',
    'vorsehen': 'haben', 'anbringen': 'haben', 'übergeben': 'haben',
    'überlassen': 'haben', 'angehen': 'sein', 'entlassen': 'haben',
    'stattfinden': 'haben', 'angreifen': 'haben', 'abgeben': 'haben',
    'berufen': 'haben', 'vorkommen': 'sein', 'ansprechen': 'haben',
    'vornehmen': 'haben', 'auffallen': 'sein', 'aufheben': 'haben',
    'mitnehmen': 'haben', 'teilnehmen': 'haben', 'empfangen': 'haben',
    'verraten': 'haben', 'anweisen': 'haben', 'anrufen': 'haben',
    'beraten': 'haben', 'bereiten': 'haben', 'aufgeben': 'haben',
    'eingehen': 'sein', 'erfinden': 'haben', 'zulassen': 'haben',
    'aufstehen': 'sein', 'vorhaben': 'haben', 'übersehen': 'haben',
    'erschießen': 'haben', 'umgeben': 'haben', 'abnehmen': 'haben',
    'begehen': 'haben', 'betreten': 'haben', 'ertragen': 'haben',
    'festnehmen': 'haben', 'nachweisen': 'haben', 'hinweisen': 'haben',
    'wahrnehmen': 'haben', 'unterschreiben': 'haben', 'verlaufen': 'sein',
    'vorliegen': 'haben', 'zugeben': 'haben', 'anziehen': 'haben',
    'entschliessen': 'haben', 'ausgeben': 'haben', 'verschieben': 'haben',
    'anschliessen': 'haben', 'festhalten': 'haben', 'vorschlagen': 'haben',
    'aufwachsen': 'sein', 'verleihen': 'haben', 'aufhalten': 'haben',
    'empfinden': 'haben', 'verschaffen': 'haben', 'unterbrechen': 'haben',
    'antreten': 'haben', 'eintragen': 'haben', 'überwinden': 'haben',
    'begreifen': 'haben', 'benennen': 'haben', 'überschreiten': 'haben',
    'ausnehmen': 'haben', 'einfallen': 'sein', 'übertreiben': 'haben',
    'aufweisen': 'haben', 'begraben': 'haben', 'zukommen': 'sein',
    'besprechen': 'haben', 'ernennen': 'haben', 'mitbringen': 'haben',
    'nachkommen': 'sein', 'vergehen': 'haben', 'aufkommen': 'sein',
    'begeben': 'haben', 'verweisen': 'haben', 'erweisen': 'haben',
    'aufrufen': 'haben', 'einnehmen': 'haben', 'verbrennen': 'haben',
    'anwenden': 'haben', 'ausfallen': 'sein', 'einsteigen': 'sein',
    'eingreifen': 'haben', 'entgehen': 'sein', 'einziehen': 'haben',
    'entnehmen': 'haben', 'eintreten': 'haben', 'entwerfen': 'haben',
    'zusehen': 'haben', 'antun': 'haben', 'einhalten': 'haben',
    'überfallen': 'haben', 'austragen': 'haben', 'entkommen': 'sein',
    'erlassen': 'haben', 'erschaffen': 'haben', 'vorwerfen': 'haben',
    'abschaffen': 'haben', 'vertreiben': 'haben', 'aushalten': 'haben',
    'entziehen': 'haben', 'unterliegen': 'haben', 'abreißen': 'haben',
    'einschließen': 'haben', 'verschließen': 'haben', 'abhalten': 'haben',
    'abziehen': 'haben', 'bestreiten': 'haben', 'einbringen': 'haben',
    'ergreifen': 'haben', 'umbringen': 'haben', 'zurückziehen': 'haben',
    'aussteigen': 'sein', 'abschneiden': 'haben', 'erleiden': 'haben',
    'versterben': 'sein', 'anhalten': 'haben', 'ausdenken': 'haben',
    'einsehen': 'haben', 'hingehen': 'sein', 'ablaufen': 'haben',
    'ausweisen': 'haben', 'ausziehen': 'sein', 'entfallen': 'sein',
    'vertragen': 'haben', 'hinnehmen': 'haben', 'aufgreifen': 'haben',
    'erziehen': 'haben', 'umziehen': 'sein', 'vorschreiben': 'haben',
    'losgehen': 'sein', 'verfallen': 'sein', 'zunehmen': 'haben',
    'überstehen': 'haben', 'abhängen': 'haben', 'ausscheiden': 'haben',
    'eintreffen': 'sein', 'aufbringen': 'haben', 'abrufen': 'haben',
    'beheben': 'haben', 'mithalten': 'haben', 'ausweichen': 'sein',
    'einschlafen': 'sein', 'erschiessen': 'haben', 'zurückgreifen': 'haben',
    'überziehen': 'haben', 'antreffen': 'haben', 'eindringen': 'sein',
    'erbringen': 'haben', 'zurückgehen': 'sein', 'zurücktreten': 'sein',
    'beschaffen': 'haben', 'durchgehen': 'sein', 'durchlaufen': 'sein',
    'herkommen': 'sein', 'wegnehmen': 'haben', 'weitergeben': 'haben',
    'zuweisen': 'haben', 'erschlagen': 'haben', 'verschreiben': 'haben',
    'zuschreiben': 'haben', 'durchziehen': 'haben', 'zurückgeben': 'haben',
    'belassen': 'haben', 'erschliessen': 'haben', 'nachgehen': 'sein',
    'überdenken': 'haben', 'überfahren': 'haben', 'abweisen': 'haben',
    'aufhängen': 'haben', 'aufsteigen': 'sein', 'vorlesen': 'haben',
    'abgehen': 'sein', 'anfahren': 'haben', 'auslassen': 'haben',
    'aussterben': 'sein', 'einlassen': 'haben', 'bekennen': 'haben',
    'verhängen': 'haben', 'vortragen': 'haben', 'abheben': 'haben',
    'anschreiben': 'haben', 'einbrechen': 'sein', 'verschweigen': 'haben',
    'vorgeben': 'haben', 'weiterhelfen': 'haben', 'zerschlagen': 'haben',
    'abschieben': 'haben', 'ausbrechen': 'haben', 'einschlagen': 'haben',
    'verbleiben': 'sein', 'zuschlagen': 'haben', 'abbrechen': 'haben',
    'begegnen': 'sein', 'erwerben': 'haben', 'bewerben': 'haben',
    'herausgeben': 'haben', 'widersprechen': 'haben', 'verbergen': 'haben',
    'herausfinden': 'haben', 'verstossen': 'haben', 'freigeben': 'haben',
    'hochladen': 'haben', 'verstoßen': 'haben', 'widerstehen': 'haben',
    'hervorheben': 'haben', 'freilassen': 'haben', 'hervorgehen': 'sein',
    'herunterladen': 'haben', 'freisprechen': 'haben', 'wiedergeben': 'haben',
    'hervorrufen': 'haben', 'wiederfinden': 'haben', 'dastehen': 'haben',
    'hervorbringen': 'haben', 'herauskommen': 'sein', 'verschmelzen': 'sein',
    'erstechen': 'haben', 'widerrufen': 'haben', 'klarkommen': 'sein',
    'anstossen': 'haben', 'preisgeben': 'haben', 'reinziehen': 'haben',
    'widerfahren': 'sein', 'herumlaufen': 'sein', 'bestechen': 'haben',
    'schiefgehen': 'sein', 'vorbeifahren': 'sein', 'fortfahren': 'sein',
    'fremdgehen': 'sein', 'herausnehmen': 'haben', 'runterfallen': 'sein',
    'zurechtkommen': 'sein', 'hochziehen': 'haben', 'reinlassen': 'haben',
    'hinzuziehen': 'haben', 'hochfahren': 'haben', 'rüberkommen': 'sein',
    'aufblasen': 'haben', 'innehalten': 'haben', 'anwerben': 'haben',
    'herankommen': 'sein', 'anfechten': 'haben', 'voranbringen': 'haben',
    'vorankommen': 'sein', 'fortgehen': 'sein', 'innehaben': 'haben',
    'grossziehen': 'haben', 'herangehen': 'sein', 'krankschreiben': 'haben',
    'schieflaufen': 'sein',
}
