"""
Manual classification of the Spanish gender residual -- nouns neither
the suffix-rule classifier nor sentence-article-extraction could
resolve. Classified from general Spanish vocabulary knowledge, word by
word. Not copied from any source; independently judged, then
cross-checked against the old (CC-BY-SA) value as a sanity check same
as the automated passes were.
"""

CLASSIFICATIONS = {
    'gente': 'f', 'dios': 'm', 'noche': 'f', 'través': 'm', 'mes': 'm',
    'web': 'f', 'paz': 'f', 'salud': 'f', 'internet': 'm', 'seis': 'm',
    'jefe': 'm', 'interés': 'm', 'siete': 'm', 'mente': 'f', 'post': 'm',
    'fe': 'f', 'habitante': 'epicene', 'carne': 'f', 'golpe': 'm',
    'café': 'm', 'nueve': 'm', 'coche': 'm', 'leche': 'f', 'blog': 'm',
    'gas': 'm', 'accidente': 'm', 'deporte': 'm', 'cumpleaños': 'm',
    'fase': 'f', 'participante': 'epicene', 'rock': 'm', 'combate': 'm',
    'pais': 'm', 'veinte': 'm', 'aceite': 'm', 'antecedente': 'm',
    'raíz': 'f', 'repente': 'm', 'fraude': 'm', 'pc': 'm', 'héroe': 'm',
    'inmigrante': 'epicene', 'arroz': 'm', 'nieve': 'f', 'combustible': 'm',
    'reloj': 'm', 'demas': 'm', 'app': 'f', 'rescate': 'm',
    'votante': 'epicene', 'gabinete': 'm', 'mate': 'm', 'uniforme': 'm',
    'occidente': 'm', 'pop': 'm', 'caos': 'm', 'té': 'm',
    'visitante': 'epicene', 'felicidades': 'f', 'incidente': 'm',
    'ave': 'f', 'aporte': 'm', 'time': 'm', 'estrés': 'm', 'nube': 'f',
    'déficit': 'm', 'pasaporte': 'm', 'anime': 'm', 'contraste': 'm',
    'japones': 'm', 'sed': 'f', 'mami': 'f', 'nazi': 'epicene',
    'constituyente': 'epicene', 'empate': 'm', 'film': 'm', 'tomate': 'm',
    'estatus': 'm', 'migrante': 'epicene', 'ray': 'm', 'wifi': 'm',
    'escape': 'm', 'id': 'm', 'papi': 'm', 'bici': 'f',
    'descendiente': 'epicene', 'bote': 'm', 'jazz': 'm', 'aguante': 'm',
    'higiene': 'f', 'dependiente': 'epicene', 'auge': 'm', 'debut': 'm',
    'manifestante': 'epicene', 'matriz': 'f', 'gripe': 'f', 'spam': 'm',
    'chip': 'm', 'rap': 'm', 'alias': 'm', 'look': 'm', 'medianoche': 'f',
    'clic': 'm', 'variante': 'f', 'merced': 'f', 'record': 'm',
    'apunte': 'm', 'diamante': 'm', 'network': 'f',
    'contribuyente': 'epicene', 'profe': 'epicene', 'inconveniente': 'm',
    'fray': 'm', 'cafe': 'm', 'guante': 'm', 'roble': 'm',
    'sobreviviente': 'epicene', 'grey': 'f', 'punk': 'm', 'res': 'f',
    'carnet': 'm', 'stock': 'm', 'ballet': 'm', 'camp': 'm', 'cómic': 'm',
    'ep': 'm', 'combatiente': 'epicene', 'pirámide': 'f', 'vip': 'epicene',
    'aspirante': 'epicene', 'celu': 'm', 'elite': 'f',
    'emigrante': 'epicene', 'sport': 'm', 'business': 'm',
    'suplente': 'epicene', 'índole': 'f', 'amateur': 'epicene',
    'empuje': 'm', 'interes': 'm', 'smartphone': 'm', 'bebe': 'm',
    'dni': 'm', 'streaming': 'm', 'videoclip': 'm', 'fé': 'f',
    'album': 'm', 'oponente': 'epicene', 'corpus': 'm', 'poniente': 'm',
    'pyme': 'f', 'acompañante': 'epicene', 'atún': 'm', 'blues': 'm',
    'desgaste': 'm', 'insurgente': 'epicene', 'ocupante': 'epicene',
    'fax': 'm', 'currículum': 'm', 'diecisiete': 'm', 'esquí': 'm',
    'banquete': 'm', 'aprendiz': 'epicene', 'ene': 'f', 'gene': 'm',
    'mix': 'm', 'mouse': 'm', 'temple': 'm', 'copyright': 'm',
    'declive': 'm', 'hit': 'm', 'covid': 'm', 'system': 'm', 'zoom': 'm',
    'comestible': 'm', 'laptop': 'f', 'nutriente': 'm',
    'oyente': 'epicene', 'surf': 'm', 'adobe': 'm', 'co2': 'm',
    'confort': 'm', 'rally': 'm', 'rompecabezas': 'm', 'site': 'm',
    'tech': 'f', 'relax': 'm', 'take': 'm', 'cash': 'm', 'change': 'm',
    'chisme': 'm', 'contingente': 'm', 'disidente': 'epicene',
    'principe': 'm', 'regente': 'epicene', 'peluche': 'm',
    'porvenir': 'm', 'hindú': 'epicene', 'western': 'm', 'compu': 'f',
    'guardaespaldas': 'epicene', 'miercoles': 'm', 'bikini': 'm',
    'holandes': 'm', 'reggae': 'm', 'restaurant': 'm', 'diecinueve': 'm',
    'forum': 'm', 'rating': 'm', 'duende': 'm', 'espiritu': 'm',
    'flote': 'm', 'jade': 'm', 'sable': 'm', 'curriculum': 'm',
    'round': 'm', 'yankee': 'epicene', 'conyuge': 'epicene',
    'fitness': 'm', 'mani': 'f', 'start': 'm', 'track': 'm',
    'burgues': 'epicene', 'interrogante': 'f', 'mp3': 'm',
    'shopping': 'm', 'band': 'f', 'contraparte': 'f', 'rascacielos': 'm',
    'bambú': 'm', 'burgués': 'epicene', 'antivirus': 'm',
    'champagne': 'm', 'estandarte': 'm', 'jarabe': 'm', 'cuatrocientos': 'm',
    'desarme': 'm', 'hobby': 'm', 'match': 'm', 'karate': 'm', 'bucle': 'm',
    'lis': 'f', 'pésame': 'm', 'zombi': 'epicene', 'camping': 'm',
    'fertilizante': 'm', 'practicante': 'epicene', 'raiz': 'f',
    'yogur': 'm', 'sabiendas': 'f', 'cliché': 'm', 'cosplay': 'm',
    'fantasy': 'f', 'secuaz': 'epicene', 'baúl': 'm', 'disparate': 'm',
    'principiante': 'epicene', 'safari': 'm', 'chalet': 'm', 'carné': 'm',
    'picnic': 'm', 'studies': 'm', 'torrent': 'm', 'collage': 'm',
    'cónyuge': 'epicene', 'desinterés': 'm', 'isp': 'm', 'maiz': 'm',
    'veintidós': 'm', 'champú': 'm', 'compas': 'm', 'stadium': 'm',
    'talle': 'm', 'tilde': 'f', 'trap': 'm', 'tórax': 'm',
    'esteroide': 'm', 'glamour': 'm', 'samurai': 'm', 'arcoiris': 'm',
    'coronavirus': 'm', 'creed': 'm', 'partícipe': 'epicene',
    'ímpetu': 'm', 'acné': 'm', 'bid': 'f', 'indigente': 'epicene',
    'travesti': 'epicene', 'arabe': 'epicene', 'graffiti': 'm',
    'resorte': 'm', 'trending': 'm', 'cabaret': 'm', 'clímax': 'm',
    'herpes': 'm', 'metrópoli': 'f', 'módem': 'm', 'rouge': 'm',
    'skate': 'm', 'confidente': 'epicene', 'contrincante': 'epicene',
    'hosting': 'm', 'pus': 'm', 'salame': 'm', 'aguardiente': 'm',
    'escaparate': 'm', 'file': 'm', 'mote': 'm', 'pretendiente': 'epicene',
    'serge': 'f', 'alarde': 'm', 'arcade': 'm', 'estupefaciente': 'm',
    'feeling': 'm', 'naipe': 'm', 'televidente': 'epicene',
    'veintitrés': 'm', 'embole': 'm', 'pope': 'm', 'stress': 'm',
    'lite': 'f', 'detergente': 'm', 'item': 'm', 'legend': 'f',
    'parking': 'm', 'coaching': 'm', 'holiday': 'f', 'hype': 'm',
    'lubricante': 'm', 'milk': 'f', 'contendiente': 'epicene',
    'estirpe': 'f', 'playlist': 'f', 'playoff': 'm', 'ítem': 'm',
    'afluente': 'm', 'pitbull': 'm', 'reproche': 'm', 'seiscientos': 'm',
    'ñoqui': 'm', 'barniz': 'm', 'brazalete': 'm', 'byte': 'm',
    'hold': 'm', 'mainstream': 'm', 'traste': 'm', 'medium': 'm',
    'talante': 'm', 'veintisiete': 'm', 'broadcasting': 'm', 'carey': 'm',
    'colorante': 'm', 'hereje': 'epicene', 'notebook': 'm',
    'pasante': 'epicene', 'puzzle': 'm', 'tiroides': 'f', 'brandy': 'm',
    'ochocientos': 'm', 'quórum': 'm', 'sake': 'm', 'tapiz': 'm',
    'veintiún': 'm', 'primate': 'm', 'arcoíris': 'm', 'kart': 'm',
    'melody': 'f', 'moment': 'm', 'tau': 'f', 'aloe': 'm', 'barrote': 'm',
    'basketball': 'm', 'consorte': 'epicene', 'efeméride': 'f',
    'impulse': 'm', 'turn': 'm', 'build': 'f', 'cache': 'm', 'compi': 'epicene',
    'guru': 'm', 'noir': 'm', 'reves': 'm', 'capi': 'epicene',
    'spirit': 'm', 'suspense': 'm', 'tramite': 'm', 'androide': 'm',
    'contratante': 'epicene', 'esfinge': 'f', 'piscis': 'm', 'airbag': 'm',
    'cent': 'm', 'guisante': 'm', 'habitat': 'm', 'necrópolis': 'f',
    'ski': 'm', 'cari': 'epicene', 'cassette': 'm', 'tándem': 'm',
    'desliz': 'm', 'kayak': 'm', 'omnibus': 'm', 'outfit': 'm',
    'catering': 'm', 'estres': 'm', 'maleante': 'epicene', 'matute': 'm',
    'arnes': 'm', 'besote': 'm', 'brocoli': 'm', 'comite': 'm',
    'compinche': 'epicene', 'mutis': 'm', 'aliciente': 'm', 'braille': 'm',
    'grafiti': 'm', 'animé': 'm', 'cofrade': 'epicene', 'ethernet': 'm',
    'refrigerante': 'm', 'celsius': 'm', 'exjefe': 'm', 'gulag': 'm',
    'hun': 'epicene', 'yihad': 'f', 'bowling': 'm', 'humus': 'm',
    'lombriz': 'f', 'snowboard': 'm', 'antidrogas': 'f', 'boxes': 'm',
    'chupete': 'm', 'desinfectante': 'm', 'lapiz': 'm', 'montañés': 'm',
    'somalí': 'epicene', 'nini': 'epicene', 'pelotudes': 'f',
    'semblante': 'm', 'whiskey': 'm', 'afrodescendiente': 'epicene',
    'albanes': 'm', 'boli': 'm', 'danzante': 'epicene', 'electronics': 'f',
    'events': 'm', 'freestyle': 'm', 'haram': 'm', 'modem': 'm',
    'pentecostés': 'm', 'pipí': 'm', 'playback': 'm', 'probe': 'f',
    'veintinueve': 'm', 'coñac': 'm', 'talent': 'm', 'contragolpe': 'm',
    'forte': 'm', 'islote': 'm', 'bíceps': 'm', 'contracorriente': 'f',
    'galope': 'm', 'maple': 'm', 'metropolis': 'f', 'monday': 'm',
    'piercing': 'm', 'pirate': 'm', 'zenit': 'm', 'chai': 'm',
    'elote': 'm', 'glam': 'm', 'grillete': 'm', 'handball': 'm',
    'hurtadillas': 'f', 'malaui': 'epicene', 'papu': 'm',
    'parachoques': 'm', 'pilates': 'm', 'sindrome': 'm', 'smog': 'm',
    'spinning': 'm', 'trend': 'f', 'cacahuete': 'm', 'calafate': 'm',
    'paté': 'm',
}
