"""
Manual classification of the French gender residual -- nouns neither
the suffix-rule classifier nor sentence-article-extraction could
resolve. Classified from general French vocabulary knowledge, word by
word. The last ~29 entries are multi-word phrases authored earlier
this session; included here as re-confirmations of prior work.
"""

CLASSIFICATIONS = {
    'temps': 'm', 'an': 'm', 'gens': 'm', 'pays': 'm', 'jour': 'm',
    'place': 'f', 'part': 'f', 'nom': 'm', 'groupe': 'm', 'famille': 'f',
    'genre': 'm', 'sens': 'm', 'jeu': 'm', 'effet': 'm', 'équipe': 'f',
    'site': 'm', 'mère': 'f', 'père': 'm', 'fille': 'f', 'problème': 'm',
    'dieu': 'm', 'fils': 'm', 'air': 'm', 'conseil': 'm', 'nuit': 'f',
    'argent': 'm', 'type': 'm', 'aide': 'f', 'retour': 'm', 'oeil': 'm',
    'amour': 'm', 'grâce': 'f', 'ordre': 'm', 'école': 'f', 'but': 'm',
    'pierre': 'f', 'art': 'm', 'chambre': 'f', 'mai': 'm', 'septembre': 'm',
    'doute': 'm', 'force': 'f', 'avis': 'm', 'juillet': 'm', 'parent': 'm',
    'abord': 'm', 'envie': 'f', 'octobre': 'm', 'avril': 'm', 'frère': 'm',
    'propos': 'm', 'âge': 'm', 'bois': 'm', 'décembre': 'm', 'novembre': 'm',
    'août': 'm', 'garde': 'f', 'internet': 'm', 'intérêt': 'm',
    'origine': 'f', 'langue': 'f', 'scène': 'f', 'second': 'm',
    'réponse': 'f', 'succès': 'm', 'espace': 'm', 'économie': 'f',
    'sorte': 'f', 'accès': 'm', 'départ': 'm', 'lit': 'm', 'numéro': 'm',
    'marque': 'f', 'pièce': 'f', 'domaine': 'm', 'matière': 'f',
    'ouest': 'm', 'permis': 'm', 'midi': 'm', 'énergie': 'f',
    'faute': 'f', 'style': 'm', 'hôtel': 'm', 'note': 'f', 'avenir': 'm',
    'preuve': 'f', 'vendredi': 'm', 'attaque': 'f', 'média': 'm',
    'habitant': 'epicene', 'vente': 'f', 'parole': 'f', 'règle': 'f',
    'objectif': 'm', 'soutien': 'm', 'course': 'f', 'mètre': 'm',
    'taille': 'f', 'visite': 'f', 'industrie': 'f', 'écoute': 'f',
    'transport': 'm', 'cheveu': 'm', 'dollar': 'm', 'hiver': 'm',
    'regard': 'm', 'habitude': 'f', 'chaîne': 'f', 'boulot': 'm',
    'madame': 'f', 'budget': 'm', 'caractère': 'm', 'mari': 'm',
    'ressource': 'f', 'revenu': 'm', 'rire': 'm', 'approche': 'f',
    'mérite': 'm', 'jeudi': 'm', 'anniversaire': 'm', 'parcours': 'm',
    'foi': 'f', 'milliard': 'm', 'sexe': 'm', 'citoyen': 'epicene',
    'maman': 'f', 'élu': 'epicene', 'empire': 'm', 'crédit': 'm',
    'méthode': 'f', 'univers': 'm', 'vice': 'm', 'écran': 'm',
    'bruit': 'm', 'conseiller': 'epicene', 'exercice': 'm', 'institut': 'm',
    'statistique': 'f', 'statut': 'm', 'domicile': 'm', 'effort': 'm',
    'employé': 'epicene', 'souvenir': 'm', 'commentaire': 'm',
    'matériel': 'm', 'sourire': 'm', 'alcool': 'm', 'agent': 'epicene',
    'impact': 'm', 'kilomètre': 'm', 'revanche': 'f', 'accueil': 'm',
    'bordel': 'm', 'colère': 'f', 'secours': 'm', 'œil': 'm', 'blague': 'f',
    'dépense': 'f', 'issue': 'f', 'échelle': 'f', 'aéroport': 'm',
    'post': 'm', 'clé': 'f', 'montagne': 'f', 'cabinet': 'm', 'faim': 'f',
    'office': 'm', 'balle': 'f', 'honte': 'f', 'huile': 'f', 'k': 'm',
    'salaire': 'm', 'épreuve': 'f', 'étoile': 'f', 'académie': 'f',
    'conduite': 'f', 'fruit': 'm', 'humour': 'm', 'informatique': 'f',
    'recours': 'm', 'épouse': 'f', 'aspect': 'm', 'bac': 'm',
    'ennemi': 'epicene', 'impôt': 'm', 'individu': 'm', 'initiative': 'f',
    'papa': 'm', 'profil': 'm', 'blog': 'm', 'neige': 'f',
    'pote': 'epicene', 'échec': 'm', 'salarié': 'epicene', 'archive': 'f',
    'orient': 'm', 'plante': 'f', 'tort': 'm', 'affiche': 'f', 'cm': 'm',
    'progrès': 'm', 'équilibre': 'm', 'attente': 'f', 'grève': 'f',
    'ombre': 'f', 'chrétien': 'epicene', 'patient': 'epicene',
    'portable': 'm', 'attitude': 'f', 'copine': 'f', 'acquis': 'm',
    'automne': 'm', 'pub': 'f', 'souci': 'm', 'désir': 'm', 'poche': 'f',
    'prénom': 'm', 'égard': 'm', 'circuit': 'm', 'feuille': 'f',
    'quart': 'm', 'trafic': 'm', 'angle': 'm', 'appui': 'm', 'récit': 'm',
    'sommeil': 'm', 'trace': 'f', 'tâche': 'f', 'automobile': 'f',
    'démarche': 'f', 'foot': 'm', 'incendie': 'm', 'prof': 'epicene',
    'abus': 'm', 'degré': 'm', 'repos': 'm', 'fonctionnaire': 'epicene',
    'lèvre': 'f', 'oreille': 'f', 'réussite': 'f', 'tir': 'm', 'tonne': 'f',
    'caméra': 'f', 'ange': 'm', 'fortune': 'f', 'océan': 'm', 'thèse': 'f',
    'trouble': 'm', 'cellule': 'f', 'hâte': 'f', 'refus': 'm',
    'souffle': 'm', 'arc': 'm', 'comédie': 'f', 'garantie': 'f',
    'diplôme': 'm', 'envoi': 'm', 'participant': 'epicene', 'évêque': 'm',
    'avenue': 'f', 'boite': 'f', 'déchet': 'm', 'oncle': 'm',
    'réfugié': 'epicene', 'allié': 'epicene', 'atmosphère': 'f',
    'charme': 'm', 'marre': 'f', 'autonomie': 'f', 'autoroute': 'f',
    'militant': 'epicene', 'adversaire': 'epicene', 'poursuite': 'f',
    'écrit': 'm', 'migrant': 'epicene', 'désert': 'm', 'enjeu': 'm',
    'jus': 'm', 'kg': 'm', 'carbone': 'm', 'flic': 'm', 'semblant': 'm',
    'beurre': 'm', 'ile': 'f', 'abbé': 'm', 'enseignant': 'epicene',
    'arbitre': 'epicene', 'banlieue': 'f', 'environs': 'm', 'légume': 'm',
    'minuit': 'm', 'métropole': 'f', 'onde': 'f', 'quête': 'f', 'baie': 'f',
    'basket': 'f', 'dégât': 'm', 'occident': 'm', 'passager': 'epicene',
    'ressort': 'm', 'ours': 'm', 'élite': 'f', 'abonné': 'epicene',
    'aube': 'f', 'bronze': 'm', 'poil': 'm', 'colonne': 'f',
    'gosse': 'epicene', 'manifestant': 'epicene', 'optique': 'f',
    'photographie': 'f', 'roue': 'f', 'veste': 'f', 'épaule': 'f',
    'colle': 'f', 'conserve': 'f', 'ecole': 'f', 'robot': 'm',
    'épargne': 'f', 'dépit': 'm', 'excès': 'm', 'manifeste': 'm',
    'conte': 'm', 'esclave': 'epicene', 'époux': 'm', 'altitude': 'f',
    'congé': 'm', 'contrainte': 'f', 'cuir': 'm', 'cv': 'm', 'herbe': 'f',
    'orchestre': 'm', 'patte': 'f', 'racine': 'f', 'assistant': 'epicene',
    'panne': 'f', 'reproche': 'm', 'asile': 'm', 'assaut': 'm',
    'crainte': 'f', 'divorce': 'm', 'délire': 'm', 'écologie': 'f',
    'fauteuil': 'm', 'réveil': 'm', 'tante': 'f', 'adn': 'm', 'colonie': 'f',
    'horaire': 'm', 'insulte': 'f', 'console': 'f', 'liège': 'm',
    'loisir': 'm', 'massacre': 'm', 'maxime': 'f', 'portefeuille': 'm',
    'refuge': 'm', 'écho': 'm', 'alentour': 'm', 'artillerie': 'f',
    'blé': 'm', 'enthousiasme': 'm', 'look': 'm', 'plomb': 'm', 'bulle': 'f',
    'faillite': 'f', 'hectare': 'm', 'historien': 'epicene',
    'poussière': 'f', 'actionnaire': 'epicene', 'agenda': 'm', 'aire': 'f',
    'chèque': 'm', 'deuil': 'm', 'fusil': 'm', 'oxygène': 'm', 'apport': 'm',
    'attache': 'f', 'gré': 'm', 'hygiène': 'f', 'manga': 'm', 'maths': 'f',
    'pme': 'f', 'alarme': 'f', 'ancêtre': 'epicene', 'céréale': 'f',
    'inquiétude': 'f', 'inventaire': 'm', 'mademoiselle': 'f',
    'solitude': 'f', 'artisan': 'epicene', 'carburant': 'm', 'cuivre': 'm',
    'dessert': 'm', 'neveu': 'm', 'chaine': 'f', 'clef': 'f',
    'empreinte': 'f', 'fibre': 'f', 'hôte': 'epicene', 'ia': 'f',
    'idéologie': 'f', 'coco': 'm', 'harmonie': 'f', 'index': 'm',
    'patrie': 'f', 'porto': 'm', 'soif': 'f', 'volet': 'm', 'cash': 'm',
    'chatte': 'f', 'concurrent': 'epicene', 'infirmière': 'f',
    'livret': 'm', 'muscle': 'm', 'ruine': 'f', 'usager': 'epicene',
    'annexe': 'f', 'archevêque': 'm', 'filet': 'm', 'obstacle': 'm',
    'pneu': 'm', 'sacrifice': 'm', 'cliché': 'm', 'data': 'f', 'duel': 'm',
    'exil': 'm', 'islamiste': 'epicene', 'nazi': 'epicene', 'botte': 'f',
    'certitude': 'f', 'estomac': 'm', 'opposant': 'epicene',
    'passeport': 'm', 'ticket': 'm', 'bonhomme': 'm', 'conjoint': 'epicene',
    'laine': 'f', 'manuscrit': 'm', 'noix': 'f', 'quarantaine': 'f',
    'amant': 'm', 'autochtone': 'epicene', 'fantôme': 'm', 'fric': 'm',
    'internaute': 'epicene', 'monarchie': 'f', 'orthographe': 'f',
    'proie': 'f', 'soie': 'f', 'amont': 'm', 'bonnet': 'm', 'char': 'm',
    'dalle': 'f', 'embauche': 'f', 'héroïne': 'f', 'intrigue': 'f',
    'autel': 'm', 'carnet': 'm', 'compagne': 'f', 'dérive': 'f',
    'encre': 'f', 'if': 'm', 'jouet': 'm', 'oubli': 'm', 'paramètre': 'm',
    'épidémie': 'f', 'aluminium': 'm', 'autobus': 'm', 'cousine': 'f',
    'instinct': 'm', 'pair': 'm', 'remède': 'm', 'routine': 'f',
    'semestre': 'm', 'bi': 'epicene', 'centimètre': 'm', 'farine': 'f',
    'résident': 'epicene', 'surnom': 'm', 'élan': 'm', 'cendre': 'f',
    'diocèse': 'm', 'protéine': 'f', 'préjugé': 'm', 'péril': 'm',
    'immigré': 'epicene', 'infanterie': 'f', 'regret': 'm', 'ete': 'm',
    'frite': 'f', 'gant': 'm', 'habit': 'm', 'ingénierie': 'f',
    'ados': 'epicene', 'gaulois': 'epicene', 'hd': 'f', 'horloge': 'f',
    'itinéraire': 'm', 'nid': 'm', 'ténèbre': 'f', 'abeille': 'f',
    'aiguille': 'f', 'boue': 'f', 'ep': 'm', 'interface': 'f',
    'orbite': 'f', 'pere': 'm', 'pipe': 'f', 'pull': 'm', 'reflet': 'm',
    'économiste': 'epicene', 'accusé': 'epicene', 'adhérent': 'epicene',
    'aéronautique': 'f', 'expo': 'f', 'ingrédient': 'm', 'maitre': 'm',
    'meuf': 'f', 'molécule': 'f', 'perle': 'f', 'single': 'm',
    'vampire': 'm', 'wall': 'm', 'bank': 'f', 'cross': 'm', 'débris': 'm',
    'ego': 'm', 'brique': 'f', 'composant': 'm', 'hydrogène': 'm',
    'hymne': 'm', 'lande': 'f', 'mamie': 'f', 'olive': 'f', 'pistolet': 'm',
    'sympathie': 'f', 'vogue': 'f', 'centime': 'm', 'equipe': 'f',
    'incertitude': 'f', 'rhétorique': 'f', 'alias': 'm', 'bactérie': 'f',
    'caca': 'm', 'contrepartie': 'f', 'gramme': 'm', 'imprimerie': 'f',
    'lycéen': 'epicene', 'désordre': 'm', 'graisse': 'f', 'gène': 'm',
    'hypocrisie': 'f', 'nièce': 'f', 'taf': 'm', 'épicerie': 'f',
    'archéologie': 'f', 'indigène': 'epicene', 'intervenant': 'epicene',
    'coulisse': 'f', 'dépens': 'm', 'homicide': 'm', 'intérim': 'm',
    'patrouille': 'f', 'relevé': 'm', 'bienfait': 'm', 'calcaire': 'm',
    'caoutchouc': 'm', 'composante': 'f', 'escorte': 'f', 'fantaisie': 'f',
    'handicapé': 'epicene', 'hebdo': 'm', 'immigrant': 'epicene',
    'iris': 'm', 'sdf': 'epicene', 'transit': 'm', 'âne': 'm', 'éco': 'f',
    'apocalypse': 'f', 'cire': 'f', 'contribuable': 'epicene',
    'drap': 'm', 'moule': 'f', 'noel': 'm', 'rempart': 'm', 'renfort': 'm',
    'tél': 'm', 'verdict': 'm', 'artifice': 'm', 'atlas': 'm',
    'audace': 'f', 'centenaire': 'epicene', 'fief': 'm', 'inconvénient': 'm',
    'ko': 'm', 'mere': 'f', 'pois': 'm', 'périphérie': 'f', 'uranium': 'm',
    'annale': 'f', 'cube': 'm', 'serie': 'f', 'éléphant': 'm',
    'céramique': 'f', 'icône': 'f', 'laisse': 'f', 'metro': 'm',
    'pipi': 'm', 'concitoyen': 'epicene', 'djihadiste': 'epicene',
    'fantasme': 'm', 'mœurs': 'f', 'pesticide': 'm', 'protestant': 'epicene',
    'pyramide': 'f', 'sourcil': 'm', 'act': 'm', 'annuaire': 'm',
    'automobiliste': 'epicene', 'book': 'm', 'cylindre': 'm',
    'energie': 'f', 'pavé': 'm', 'qi': 'm', 'vestige': 'm', 'consigne': 'f',
    'constituant': 'm', 'entrepôt': 'm', 'extrémiste': 'epicene',
    'fiancé': 'epicene', 'milliardaire': 'epicene', 'représaille': 'f',
    'rhum': 'm', 'rime': 'f', 'éponge': 'f', 'aimant': 'm', 'aout': 'm',
    'designer': 'epicene', 'débutant': 'epicene', 'etude': 'f',
    'figurant': 'epicene', 'fringue': 'f', 'rente': 'f', 'scooter': 'm',
    'variante': 'f', 'écurie': 'f', 'arche': 'f', 'argile': 'f',
    'arène': 'f', 'barbare': 'epicene', 'bot': 'm', 'cl': 'm',
    'cursus': 'm', 'drama': 'm', 'fantasy': 'f', 'hébreu': 'm',
    'idole': 'f', 'niche': 'f', 'écosystème': 'm', 'évangile': 'm',
    'anatomie': 'f', 'blocus': 'm', 'coke': 'm', 'north': 'm',
    'spirale': 'f', 'électro': 'f', 'algorithme': 'm', 'boeuf': 'm',
    'cadet': 'epicene', 'chevet': 'm', 'chips': 'f', 'chrome': 'm',
    'enseigne': 'f', 'episode': 'm', 'gout': 'm', 'orgue': 'm',
    'orgueil': 'm', 'switch': 'm', 'tank': 'm', 'traître': 'epicene',
    'appelé': 'm', 'artère': 'f', 'aurore': 'f', 'calorie': 'f',
    'capitaliste': 'epicene', 'commis': 'm', 'engrais': 'm', 'logis': 'm',
    'martyr': 'epicene', 'ml': 'm', 'avatar': 'm', 'aveu': 'm',
    'carotte': 'f', 'cola': 'm', 'minerai': 'm', 'url': 'f',
    'whisky': 'm', 'éloge': 'm', 'alphabet': 'm', 'antisémite': 'epicene',
    'barbarie': 'f', 'biscuit': 'm', 'condé': 'm', 'encyclopédie': 'f',
    'lentille': 'f', 'math': 'f', 'slip': 'm', 'urine': 'f', 'épice': 'f',
    'coloris': 'm', 'garant': 'epicene', 'honoraire': 'm', 'hormone': 'f',
    'patate': 'f', 'ressortissant': 'epicene', 'villageois': 'epicene',
    'vinaigre': 'm', 'algue': 'f', 'anthropologie': 'f', 'anus': 'm',
    'atome': 'm', 'azote': 'm', 'bagnole': 'f', 'chariot': 'm',
    'impératrice': 'f', 'messagerie': 'f', 'orge': 'f', 'pole': 'm',
    'préparatif': 'm', 'velours': 'm', 'vignoble': 'm', 'antécédent': 'm',
    'griffe': 'f', 'imagerie': 'f', 'juriste': 'epicene', 'octroi': 'm',
    'piece': 'f', 'préavis': 'm', 'toc': 'm', 'apprenti': 'epicene',
    'neurone': 'm', 'zinc': 'm', 'abruti': 'epicene', 'actu': 'f',
    'ampoule': 'f', 'corne': 'f', 'edit': 'm', 'grès': 'm', 'imam': 'm',
    'insurgé': 'epicene', 'ouragan': 'm', 'quota': 'm', 'suspense': 'm',
    'gendre': 'm', 'obsèque': 'f', 'plant': 'm', 'porcelaine': 'f',
    'résidu': 'm', 'suspens': 'm', 'votant': 'epicene', 'analyste': 'epicene',
    'astronomie': 'f', 'calcium': 'm', 'dune': 'f', 'embarras': 'm',
    'finaliste': 'epicene', 'forge': 'f', 'haricot': 'm', 'énoncé': 'm',
    'épave': 'f', 'érable': 'm', 'cognac': 'm', 'empathie': 'f',
    'exode': 'm', 'export': 'm', 'haram': 'm', 'plasma': 'm',
    'remords': 'm', 'apôtre': 'm', 'courtoisie': 'f', 'escroc': 'epicene',
    'lotus': 'm', 'mate': 'm', 'minima': 'm', 'pou': 'm', 'pouls': 'm',
    'prépa': 'f', 'pus': 'm', 'pyjama': 'm', 'utérus': 'm', 'égide': 'f',
    'ancre': 'f', 'blabla': 'm', 'correspondant': 'epicene', 'cuve': 'f',
    'homophobie': 'f', 'mama': 'f', 'muse': 'f', 'papy': 'm',
    'périple': 'm', 'retrouvaille': 'f', 'trompe': 'f', 'émissaire': 'm',
    'kids': 'm', 'latino': 'epicene', 'orgasme': 'm', 'sorcellerie': 'f',
    'vitamine': 'f', 'wc': 'm', 'abdomen': 'm', 'dentelle': 'f',
    'hexagone': 'm', 'oracle': 'm', 'voirie': 'f', 'zénith': 'm',
    'amphithéâtre': 'm', 'badge': 'm', 'dogme': 'm', 'emblème': 'm',
    'gene': 'm', 'granit': 'm', 'infirmerie': 'f', 'matos': 'm',
    'mercenaire': 'epicene', 'prophétie': 'f', 'schiste': 'm',
    'stéréotype': 'm', 'taule': 'f', 'éolienne': 'f', 'éveil': 'm',
    'ananas': 'm', 'anarchie': 'f', 'aquarium': 'm', 'cosmétique': 'm',
    'enclos': 'm', 'exploitant': 'epicene', 'gratitude': 'f',
    'hôtellerie': 'f', 'imprimante': 'f', 'licorne': 'f', 'market': 'm',
    'parapluie': 'm', 'pige': 'f', 'adultère': 'm', 'armistice': 'm',
    'déontologie': 'f', 'manège': 'm', 'contrebande': 'f', 'controle': 'm',
    'différend': 'm', 'escrime': 'f', 'fax': 'm', 'fresque': 'f',
    'homologue': 'epicene', 'identifiant': 'm', 'infographie': 'f',
    'marraine': 'f', 'millionnaire': 'epicene', 'oie': 'f', 'bebe': 'm',
    'credit': 'm', 'gréviste': 'epicene', 'hémorragie': 'f', 'ocean': 'm',
    'peluche': 'f', 'rebours': 'm', 'teen': 'epicene', 'ere': 'f',
    'amorce': 'f', 'beta': 'm', 'bille': 'f', 'debut': 'm', 'parachute': 'm',
    'pousse': 'f', 'rechange': 'm', 'régent': 'm', 'trousse': 'f',
    'abîme': 'm', 'agonie': 'f', 'amiante': 'm', 'apartheid': 'm',
    'effigie': 'f', 'fable': 'f', 'figurine': 'f', 'hémisphère': 'm',
    'pli': 'm', 'riposte': 'f', 'répit': 'm', 'tourmente': 'f',
    'vinyle': 'm', 'vrac': 'm', 'adrénaline': 'f', 'amplitude': 'f',
    'aristocratie': 'f', 'asthme': 'm', 'astronaute': 'epicene',
    'caste': 'f', 'débouché': 'm', 'entraide': 'f', 'ethnie': 'f',
    'islamophobie': 'f', 'muraille': 'f', 'substitut': 'm', 'catch': 'm',
    'hate': 'f', 'intempérie': 'f', 'paradigme': 'm', 'parme': 'm',
    'scene': 'f', 'tata': 'f', 'town': 'f', 'tôle': 'f', 'watt': 'm',
    'zèle': 'm', 'égout': 'm', 'academy': 'f', 'bit': 'm', 'envol': 'm',
    'euthanasie': 'f', 'fitness': 'm', 'inculpé': 'epicene',
    'intendant': 'epicene', 'mafieux': 'epicene', 'mandataire': 'epicene',
    'polar': 'm', 'pétale': 'm', 'scellé': 'm', 'aléa': 'm', 'ambre': 'm',
    'anticorps': 'm', 'archer': 'epicene', 'baril': 'm', 'cake': 'm',
    'centriste': 'epicene', 'guardian': 'm', 'intro': 'f',
    'maniere': 'f', 'numero': 'm', 'opera': 'm', 'pancarte': 'f',
    'papi': 'm', 'physicien': 'epicene', 'pourparler': 'm',
    'séquelle': 'f', 'uv': 'm', 'veto': 'm', 'écorce': 'f',
    'collégien': 'epicene', 'fiasco': 'm', 'gluten': 'm', 'guérilla': 'f',
    'noeud': 'm', 'nouille': 'f', 'plaidoyer': 'm', 'pong': 'm',
    'péripétie': 'f', 'ride': 'f', 'écuyer': 'm', 'coloc': 'epicene',
    'ecologie': 'f', 'huître': 'f', 'mire': 'f', 'offshore': 'm',
    'omega': 'm', 'opium': 'm', 'oxyde': 'm', 'rêne': 'f', 'amande': 'f',
    'attaquant': 'epicene', 'flingue': 'm', 'kw': 'm', 'maille': 'f',
    'meme': 'm', 'méfait': 'm', 'paupière': 'f', 'pixel': 'm',
    'tandem': 'm', 'égoïsme': 'm', 'hypnose': 'f', 'lux': 'm', 'paye': 'f',
    "prud'homme": 'm', 'role': 'm', 'sifflet': 'm', 'traite': 'f',
    'étendard': 'm', 'étymologie': 'f', 'adjudant': 'm', 'affût': 'm',
    'avoine': 'f', 'bitume': 'm', 'bluff': 'm', 'convive': 'epicene',
    'graphiste': 'epicene', 'hystérie': 'f', 'modestie': 'f', 'thorax': 'm',
    'tract': 'm', 'bohème': 'epicene', 'djihad': 'm', 'elfe': 'm',
    'facho': 'epicene', 'gauchiste': 'epicene', 'holocauste': 'm',
    'hégémonie': 'f', 'métis': 'epicene', 'orteil': 'm', 'racaille': 'f',
    'alchimie': 'f', 'archéologue': 'epicene', 'astrologie': 'f',
    'costard': 'm', 'entraille': 'f', 'item': 'm', 'lacet': 'm',
    'rubis': 'm', 'référentiel': 'm', 'stéréo': 'f', 'tripe': 'f',
    'dignitaire': 'm', 'electro': 'f', 'escadre': 'f',
    'institutrice': 'f', 'jihad': 'm', 'mémé': 'f', 'reponse': 'f',
    'sante': 'f', 'tromperie': 'f', 'blogue': 'm', 'bâtisse': 'f',
    'capuche': 'f', 'elite': 'f', 'hépatite': 'f', 'import': 'm',
    'left': 'f', 'lex': 'f', 'paie': 'f', 'remous': 'm', 'reptile': 'm',
    'rouille': 'f', 'sandale': 'f', 'vendange': 'f', 'épine': 'f',
    'affluent': 'm', 'alto': 'm', 'aquarelle': 'f', 'briquet': 'm',
    'envi': 'f', 'hospice': 'm', 'insuline': 'f', 'paranoïa': 'f',
    'évêché': 'm', 'bouddhiste': 'epicene', 'cavale': 'f',
    'cholestérol': 'm', 'daddy': 'm', 'dia': 'f', 'effect': 'm',
    'exergue': 'm', 'flyer': 'm', 'hype': 'm', 'hélice': 'f',
    'iceberg': 'm', 'inceste': 'm', 'ozone': 'm', 'styliste': 'epicene',
    'theatre': 'm', 'thune': 'f', 'électricien': 'epicene', 'abs': 'm',
    'acronyme': 'm', 'armoirie': 'f', 'astronome': 'epicene',
    'cocotte': 'f', 'extase': 'f', 'insomnie': 'f', 'intrus': 'epicene',
    'louange': 'f', 'matraque': 'f', 'microbe': 'm', 'playoffs': 'm',
    'repaire': 'm', 'scrupule': 'm', 'turbine': 'f', 'ut': 'm',
    'étagère': 'f', 'banderole': 'f', 'cachemire': 'm', 'etranger': 'm',
    'galet': 'm', 'lieue': 'f', 'lilas': 'm', 'méta': 'f', 'ouïe': 'f',
    'richards': 'm', 'sushi': 'm', 'tulle': 'm', 'étui': 'm', 'appoint': 'm',
    'bave': 'f', 'domino': 'm', 'héro': 'm', 'scotch': 'm', 'émir': 'm',
    'appât': 'm', 'brio': 'm', 'cout': 'm', 'décombre': 'm', 'ecran': 'm',
    'escargot': 'm', 'euphorie': 'f', 'foret': 'f', 'guignol': 'm',
    'shield': 'm', 'weed': 'f', 'épilepsie': 'f', 'antre': 'm', 'croc': 'm',
    'doudou': 'm', 'exposant': 'm', 'gamma': 'm', 'horlogerie': 'f',
    'hyacinthe': 'f', 'log': 'm', 'sunnite': 'epicene', 'sésame': 'm',
    'tact': 'm', 'volt': 'm', 'écaille': 'f', 'algèbre': 'f',
    'asphalte': 'm', 'bale': 'f', 'beauf': 'm', 'binôme': 'm',
    'epargne': 'f', 'fût': 'm', 'lucarne': 'f', 'malice': 'f', 'ogre': 'm',
    'oued': 'm', 'paperasse': 'f', 'pastel': 'm', 'placebo': 'm',
    'pétard': 'm', 'arithmétique': 'f', 'assaillant': 'epicene',
    'cacahuète': 'f', 'crotte': 'f', 'dote': 'f', 'encens': 'm',
    'fougère': 'f', 'globule': 'm', 'gnu': 'm', 'hémicycle': 'm',
    'loulou': 'm', 'panache': 'm', 'précepte': 'm', 'spaghetti': 'm',
    'tournesol': 'm', 'tune': 'f', 'xxl': 'm', 'colo': 'f', 'dej': 'm',
    'hippie': 'epicene', 'javel': 'f', 'joyau': 'm', 'matricule': 'm',
    'omnium': 'm', 'syllabe': 'f', 'verve': 'f', 'argot': 'm', 'astre': 'm',
    'auditorium': 'm', 'credo': 'm', 'crustacé': 'm', 'encours': 'm',
    'feuillet': 'm', 'habitacle': 'm', 'hippodrome': 'm', 'lumiere': 'f',
    'mousquetaire': 'm', 'omc': 'f', 'republique': 'f', 'theme': 'm',
    'vod': 'f', 'acné': 'f', 'autruche': 'f', 'calculatrice': 'f',
    'estuaire': 'm', 'fougue': 'f', 'frérot': 'm', 'harmattan': 'm',
    'interet': 'm', 'intégriste': 'epicene', 'orgie': 'f', 'quad': 'm',
    'égo': 'm', 'antidote': 'm', 'autocar': 'm', 'faste': 'm', 'ire': 'f',
    'menotte': 'f', 'oméga': 'm', 'sanglot': 'm', 'sardine': 'f',
    'traverse': 'f', 'épinard': 'm', 'celte': 'epicene', 'furie': 'f',
    'grief': 'm', 'hobbit': 'm', 'iconographie': 'f', 'mollusque': 'm',
    'ovaire': 'm', 'prémice': 'f', 'therme': 'm', 'tropique': 'm',
    'vrille': 'f', 'électroménager': 'm', 'apache': 'm', 'archiduc': 'm',
    'arsenic': 'm', 'asphyxie': 'f', 'aune': 'f', 'betterave': 'f',
    'démagogie': 'f', 'enzyme': 'f', 'gitan': 'epicene', 'glucide': 'm',
    'jasper': 'm', 'paroissien': 'epicene', 'retouche': 'f', 'salam': 'm',
    'tele': 'f', 'traitre': 'epicene', 'égérie': 'f', 'agora': 'f',
    'alcoolémie': 'f', 'amazone': 'f', 'anatomy': 'f', 'archiviste': 'epicene',
    'arret': 'm', 'brouille': 'f', 'cafe': 'm', 'disgrâce': 'f',
    'echange': 'm', 'effroi': 'm', 'gué': 'm', 'journee': 'f',
    'magouille': 'f', 'nada': 'm', 'orthodoxie': 'f', 'phosphate': 'm',
    'pitch': 'm', 'épilogue': 'm', 'amadou': 'm', 'armada': 'f',
    'brick': 'm', 'dada': 'm', 'ecolo': 'epicene', 'etudiant': 'epicene',
    'hamster': 'm', 'hobby': 'm', 'iode': 'm', 'papille': 'f',
    'paroxysme': 'm', 'plénitude': 'f', 'pore': 'm', 'taco': 'm',
    'target': 'f', 'tong': 'f', 'trap': 'm', 'cassis': 'm',
    'chimiothérapie': 'f', 'duvet': 'm', 'foetus': 'm', 'hélium': 'm',
    'persil': 'm', 'racket': 'm', 'resource': 'f', 'reve': 'm', 'acre': 'f',
    'archétype': 'm', 'colorant': 'm', 'congénère': 'epicene',
    'freestyle': 'm', 'héroïsme': 'm', 'incognito': 'm', 'intox': 'f',
    'lino': 'm', 'lira': 'f', 'mob': 'f', 'pédiatrie': 'f', 'sarcasme': 'm',
    'silicone': 'f', 'transe': 'f', 'acolyte': 'epicene', 'chromosome': 'm',
    'contrebas': 'm', 'detective': 'epicene', 'granite': 'm', 'inox': 'm',
    'monoprix': 'm', 'méduse': 'f', 'root': 'm', 'référent': 'm',
    'sinus': 'm', 'tique': 'f', 'travesti': 'epicene', 'écume': 'f',
    'épi': 'm', 'épiderme': 'm', 'aid': 'm', 'amnésie': 'f',
    'appendice': 'm', 'arriere': 'm', 'chapelet': 'm', 'confident': 'epicene',
    'deco': 'f', 'drag': 'm', 'ergonomie': 'f', 'eucharistie': 'f',
    'gone': 'epicene', 'guillemet': 'm', 'malt': 'm', 'pulpe': 'f',
    'rider': 'epicene', 'agrume': 'm', 'anguille': 'f', 'antipode': 'm',
    'anémie': 'f', 'aristocrate': 'epicene', 'cle': 'f', 'eldorado': 'm',
    'emphase': 'f', 'friche': 'f', 'gourde': 'f', 'impayé': 'm',
    'modele': 'm', 'moquerie': 'f', 'physionomie': 'f', 'planque': 'f',
    'toutou': 'm', 'étable': 'f', 'aisselle': 'f', 'escient': 'm',
    'lipide': 'm', 'mst': 'f', 'mvp': 'm', 'nounours': 'm',
    'officine': 'f', 'patronyme': 'm', 'prune': 'f', 'recel': 'm',
    'édito': 'm', 'électrode': 'f', 'académicien': 'epicene', 'acces': 'm',
    'aumône': 'f', 'aéronef': 'm', 'aïeul': 'epicene', 'colza': 'm',
    'détritus': 'm', 'electronic': 'f', 'frere': 'm', 'indus': 'm',
    'méandre': 'm', 'pantoufle': 'f', 'sbire': 'm', 'éditorialiste': 'epicene',
    'éther': 'm', 'anis': 'm', 'apothéose': 'f', 'archange': 'm',
    'archevêché': 'm', 'autodéfense': 'f', 'banco': 'm', 'béquille': 'f',
    'colocataire': 'epicene', 'dol': 'm', 'guirlande': 'f',
    'homéopathie': 'f', 'lest': 'm', 'mana': 'm', 'numéraire': 'm',
    'resident': 'epicene', 'silo': 'm', 'tentacule': 'm',
    'apathie': 'f', 'auspice': 'm', 'barbelé': 'm', 'bribe': 'f',
    'decembre': 'm', 'desire': 'm', 'eclipse': 'f', 'foutais': 'f',
    'hosto': 'm', 'jubilé': 'm', 'legumineuse': 'f', 'occitan': 'm',
    'rapatrié': 'epicene', 'rosaire': 'm', 'sourate': 'f', 'étau': 'm',
    'additif': 'm', 'apex': 'm', 'copropriétaire': 'epicene', 'esport': 'm',
    'ethnologie': 'f', 'exam': 'm', 'exécutant': 'epicene',
    'insecticide': 'm', 'liner': 'm', 'lyric': 'f', 'mano': 'f',
    'medicine': 'f', 'pupitre': 'm', 'quenelle': 'f', 'seigle': 'm',
    'silice': 'f', 'acquit': 'm', 'besogne': 'f', 'bigot': 'epicene',
    'buis': 'm', 'bulbe': 'm', 'calomnie': 'f', 'dard': 'm', 'depart': 'm',
    'dico': 'm', 'fenetre': 'f', 'flamenco': 'm', 'goulag': 'm',
    'hostie': 'f', 'kiwi': 'm', 'latte': 'f', 'navet': 'm', 'orfèvre': 'm',
    'radis': 'm', 'sociétaire': 'epicene', 'vertébré': 'm', 'anorexie': 'f',
    'ara': 'm', 'astreinte': 'f', 'cabernet': 'm', 'cerne': 'm',
    'confédéré': 'm', 'gamelle': 'f', 'horloger': 'epicene', 'impro': 'f',
    'infante': 'f', 'kappa': 'm', 'lotto': 'm', 'mach': 'm', 'martien': 'epicene',
    'maxim': 'f', 'maxima': 'm', 'optimum': 'm', 'primate': 'm',
    'tracas': 'm', 'vergogne': 'f', 'zodiac': 'm', 'écluse': 'f',
    'aspirine': 'f', 'avent': 'm', 'banqueroute': 'f', 'bidonville': 'm',
    'braille': 'm', 'catacombe': 'f', 'essieu': 'm', 'eucalyptus': 'm',
    'exo': 'm', 'gestuelle': 'f', 'huguenot': 'epicene', 'koi': 'm',
    'meule': 'f', 'nugget': 'm', 'oléoduc': 'm', 'polymère': 'm',
    'securite': 'f', 'spore': 'f', 'sucrerie': 'f', 'titi': 'm',
    'évangéliste': 'epicene', 'aine': 'f', 'almanach': 'm', 'arn': 'm',
    'automate': 'm', 'aïd': 'm', 'clipper': 'm', 'container': 'm',
    'cosaque': 'm', 'doudoune': 'f', 'démêlé': 'm', 'granule': 'm',
    'historiographie': 'f', 'mainstream': 'm', 'organigramme': 'm',
    'ortie': 'f', 'portfolio': 'm', 'radiothérapie': 'f', 'sévices': 'm',
    'vandale': 'epicene', 'ébène': 'f', 'épithète': 'f', 'antichambre': 'f',
    'astro': 'm', 'filleul': 'm', 'glaive': 'm', 'harem': 'm',
    'inca': 'epicene', 'inconfort': 'm', 'nitrate': 'm', 'nymphe': 'f',
    'ouzou': 'm', 'pépé': 'm', 'quorum': 'm', 'ria': 'f', 'sneaker': 'f',
    'stéroïde': 'm', 'épargnant': 'epicene', 'épouvante': 'f',
    'apostasie': 'f', 'arthrite': 'f', 'assistante': 'f', 'biceps': 'm',
    'cel': 'm', 'contrefort': 'm', 'cyprès': 'm', 'désintérêt': 'm',
    'echelle': 'f', 'embûche': 'f', 'hectolitre': 'm', 'hirondelle': 'f',
    'hétérosexuel': 'epicene', 'ibis': 'm', 'interné': 'epicene',
    'maker': 'epicene', 'ogive': 'f', 'raptor': 'm', 'écueil': 'm',
    'éthanol': 'm', 'acacia': 'm', 'ammoniac': 'm', 'distillerie': 'f',
    'genie': 'm', 'homonyme': 'm', 'idol': 'f', 'indie': 'm', 'mdp': 'm',
    'mécréant': 'epicene', 'régente': 'f', 'sinistré': 'epicene',
    'steppe': 'f', 'upload': 'm', 'épître': 'f', 'acajou': 'm',
    'asperge': 'f', 'bouille': 'f', 'cinquantenaire': 'm', 'exégèse': 'f',
    'flashback': 'm', 'froc': 'm', 'hermine': 'f', 'hydrate': 'm',
    'hémoglobine': 'f', 'interim': 'm', 'ivrogne': 'epicene', 'lierre': 'm',
    'montagnard': 'epicene', 'muslim': 'epicene', 'oligarque': 'epicene',
    'partant': 'm', 'poid': 'm', 'sheikh': 'm', 'échine': 'f', 'abside': 'f',
    'aidant': 'epicene', 'arachide': 'f', 'bleuet': 'm', 'cartable': 'm',
    'cosplay': 'm', 'curriculum': 'm', 'emir': 'm', 'fjord': 'm',
    'graphite': 'm', 'herpès': 'm', 'nordiste': 'epicene',
    'organiste': 'epicene', 'percent': 'm', 'peso': 'm', 'publi': 'f',
    'pvc': 'm', 'renne': 'm', 'réserviste': 'epicene', 'séquestre': 'm',
    'tuque': 'f', 'apens': 'm', 'arbalète': 'f', 'astrophysique': 'f',
    'bottine': 'f', 'bureautique': 'f', 'cigale': 'f', 'désuétude': 'f',
    'hyperbole': 'f', 'infinitif': 'm', 'orque': 'f', 'quille': 'f',
    'scenario': 'm', 'stimulus': 'm', 'tète': 'f', 'usufruit': 'm',
    'boucan': 'm', 'cosse': 'f', 'cyclo': 'm', 'cédé': 'm', 'dome': 'm',
    'druide': 'm', 'escadrille': 'f', 'néophyte': 'epicene', 'oseille': 'f',
    'rizière': 'f', 'tangente': 'f', 'argus': 'm', 'boiserie': 'f',
    'bru': 'f', 'calèche': 'f', 'cardiologue': 'epicene', 'cervicale': 'f',
    'ecoute': 'f', 'fumigène': 'm', 'giga': 'm', 'landau': 'm',
    'obstétrique': 'f', 'paparazzi': 'm', 'pèche': 'f', 'rtt': 'f',
    'soviet': 'm', 'subconscient': 'm', 'épitaphe': 'f', 'agronome': 'epicene',
    'biere': 'f', 'coli': 'm', 'corinthien': 'epicene', 'croche': 'f',
    'datte': 'f', 'discographie': 'f', 'enquete': 'f', 'entropie': 'f',
    'filmographie': 'f', 'glycémie': 'f', 'hippopotame': 'm', 'oranger': 'm',
    'orbe': 'm', 'share': 'm', 'suede': 'm', 'tilt': 'm', 'tirelire': 'f',
    'aboi': 'm', 'alchimiste': 'epicene', 'anchois': 'm', 'antithèse': 'f',
    'bete': 'f', 'caractere': 'm', 'celibataire': 'epicene', 'harmonica': 'm',
    'inaptitude': 'f', 'invendu': 'm', 'mam': 'f', 'mantra': 'm',
    'oncologie': 'f', 'pillard': 'epicene', 'qualite': 'f', 'ragot': 'm',
    'ravioli': 'm', 'rebel': 'epicene', 'sudiste': 'epicene', 'écrou': 'm',
    'épistémologie': 'f', 'aborigène': 'epicene', 'ante': 'f', 'auge': 'f',
    'boyard': 'm', 'bran': 'm', 'bâtonnet': 'm', 'cherie': 'f',
    'chronomètre': 'm', 'crunch': 'm', 'entracte': 'm', 'gencive': 'f',
    'hypermarché': 'm', 'inuit': 'epicene', 'jacquard': 'm', 'julienne': 'f',
    'lesbien': 'epicene', 'liane': 'f', 'license': 'f', 'logic': 'f',
    'maroquinerie': 'f', 'merlot': 'm', 'methode': 'f', 'mirabel': 'f',
    'ourse': 'f', 'ovule': 'm', 'patriot': 'm', 'peche': 'f', 'pégase': 'm',
    'rogne': 'f', 'spartiate': 'epicene', 'tribord': 'm', 'épicentre': 'm',
    'abricot': 'm', 'absinthe': 'f', 'aorte': 'f', 'aubergine': 'f',
    'carre': 'm', 'chaume': 'm', 'courroux': 'm', 'dialyse': 'f',
    'electronique': 'f', 'ester': 'm', 'joujou': 'm', 'jute': 'm',
    'limace': 'f', 'matiere': 'f', 'meteo': 'f', 'metropolis': 'f',
    'méninge': 'f', 'opticien': 'epicene', 'pastis': 'm', 'ronce': 'f',
    'shea': 'm', 'tapa': 'f', 'tonus': 'm', 'apostrophe': 'f',
    'autours': 'm', 'contumace': 'f', 'hipster': 'epicene', 'inspectrice': 'f',
    'liberte': 'f', 'lymphocyte': 'm', 'millionaire': 'epicene',
    'myopie': 'f', 'nacre': 'f', 'pancake': 'm', 'subprime': 'm',
    'swap': 'm', 'termite': 'f', 'thermidor': 'm', 'zenith': 'm',
    'affre': 'f', 'ammonium': 'm', 'atrium': 'm', 'boomer': 'epicene',
    'cannibale': 'epicene', 'collabo': 'epicene', 'exoplanète': 'f',
    'feedback': 'm', 'orfèvrerie': 'f', 'pavot': 'm', 'polyester': 'm',
    'succes': 'm', 'tulipe': 'f', 'albatros': 'm', 'brac': 'm', 'fiel': 'm',
    'goth': 'epicene', 'guimauve': 'f', 'hadith': 'm', 'hare': 'f',
    'humus': 'm', 'isthme': 'm', 'lithographie': 'f', 'opprobre': 'm',
    'pilotis': 'm', 'spleen': 'm', 'survivor': 'epicene', 'sénior': 'epicene',
    'turk': 'epicene', 'abysse': 'm', 'acarien': 'm', 'acropole': 'f',
    'agronomie': 'f', 'aubergiste': 'epicene', 'bureaucrate': 'epicene',
    'champenois': 'epicene', 'confetti': 'm', 'copte': 'epicene',
    'entête': 'm', 'hamac': 'm', 'harki': 'm', 'hymen': 'm',
    'instit': 'epicene', 'justiciable': 'epicene', 'lifestyle': 'm',
    'nao': 'f', 'ophtalmo': 'epicene', 'orangerie': 'f', 'pirogue': 'f',
    'rais': 'm', 'sangsue': 'f', 'sheriff': 'm', 'stalker': 'epicene',
    'strass': 'm', 'twittos': 'epicene', 'épidémiologie': 'f',
    'affect': 'm', 'alpiniste': 'epicene', 'andouille': 'f',
    'anesthésiste': 'epicene', 'animalerie': 'f', 'atlantide': 'f',
    'avarice': 'f', 'azimut': 'm', 'bimbo': 'f', 'bop': 'm', 'cheyenne': 'epicene',
    'cochonnerie': 'f', 'elephant': 'm', 'enclume': 'f',
    'esthéticienne': 'f', 'hydre': 'f', 'infortune': 'f', 'intrant': 'm',
    'merguez': 'f', 'metre': 'm', 'psychotrope': 'm', 'quadrilatère': 'm',
    'russian': 'epicene', 'rut': 'm', 'serf': 'm', 'universite': 'f',
    'volute': 'f', 'acétate': 'm', 'agar': 'm', 'alligator': 'm',
    'broussaille': 'f', 'defaut': 'm', 'déodorant': 'm', 'eczéma': 'm',
    'embrun': 'm', 'entrejambe': 'm', 'ethnographie': 'f', 'greve': 'f',
    'intelligentsia': 'f', 'noz': 'f', 'pater': 'm', 'philanthropie': 'f',
    'platane': 'm', 'pulp': 'f', 'suie': 'f', 'superhéros': 'm',
    'toupie': 'f', 'échafaud': 'm', 'academie': 'f', 'aga': 'm',
    'arcane': 'm', 'archet': 'm', 'badaud': 'epicene', 'bayou': 'm',
    'capucine': 'f', 'conifère': 'm', 'depot': 'm', 'docker': 'm',
    'eunuque': 'm', 'hiéroglyphe': 'm', 'ineptie': 'f', 'infant': 'm',
    'katana': 'm', 'myrtille': 'f', 'mégot': 'm', 'obélisque': 'm',
    'parque': 'f', 'pony': 'm', 'prenom': 'm', 'prérequis': 'm',
    'pére': 'm', 'strophe': 'f', 'tanière': 'f', 'theorie': 'f',
    'abstentionniste': 'epicene', 'apprenant': 'epicene', 'ayatollah': 'm',
    'châtaigne': 'f', 'cine': 'm', 'colere': 'f', 'commandite': 'f',
    'cops': 'm', 'frasque': 'f', 'hypothermie': 'f', 'latrine': 'f',
    'nécrologie': 'f', 'parcimonie': 'f', 'polichinelle': 'm', 'spec': 'f',
    'archidiacre': 'm', 'chakra': 'm', 'herbivore': 'm', 'luciole': 'f',
    'mojo': 'm', 'sanatorium': 'm', 'soy': 'm', 'subject': 'm',
    'urbaniste': 'epicene', 'étamine': 'f', 'aeroport': 'm', 'airbag': 'm',
    'ane': 'm', 'bandoulière': 'f', 'bricole': 'f', 'calanque': 'f',
    'camomille': 'f', 'ecstasy': 'f', 'entree': 'f', 'fallout': 'm',
    'herbicide': 'm', 'hooligan': 'm', 'mesa': 'f', 'musc': 'm',
    'proces': 'm', 'resume': 'm', 'rivet': 'm', 'rune': 'f',
    'résidant': 'epicene', 'sitcom': 'f', 'sobriquet': 'm', 'troubadour': 'm',
    'tréfond': 'm', 'végétalien': 'epicene', 'wax': 'm', 'aboutissant': 'm',
    'antéchrist': 'm', 'bouseux': 'epicene', 'brandy': 'm',
    'carotide': 'f', 'courtisan': 'm', 'hippocampe': 'm', 'madras': 'm',
    'magnéto': 'm', 'omerta': 'f', 'oriole': 'm', 'ouate': 'f',
    'prudhomme': 'm', 'royaltie': 'f', 'stups': 'm', 'tweed': 'm',
    'vanilla': 'f', 'vicissitude': 'f', 'vinyl': 'm', 'vêpre': 'f',
    'épiphanie': 'f', 'allocataire': 'epicene', 'arpent': 'm',
    'bronche': 'f', 'butch': 'epicene', 'causse': 'm', 'epreuve': 'f',
    'girofle': 'f', 'grid': 'f', 'indiscipline': 'f', 'invective': 'f',
    'invertébré': 'm', 'lensois': 'epicene', 'milligramme': 'm',
    'mimique': 'f', 'opiacé': 'm', 'pigiste': 'epicene', 'puit': 'm',
    'victory': 'f', 'vitriol': 'm', 'acrobate': 'epicene', 'acrobatie': 'f',
    'apothicaire': 'epicene', 'astérisque': 'm', 'bâbord': 'm', 'evêque': 'm',
    'glam': 'm', 'ophtalmologie': 'f', 'penne': 'f', 'popper': 'm',
    'pylône': 'm', 'sect': 'f', 'soap': 'm', 'surcroit': 'm',
    'technocrate': 'epicene', 'transfer': 'm', 'urticaire': 'f',
    'zouave': 'm', 'électrolyse': 'f', 'apatride': 'epicene',
    'autocritique': 'f', 'barrique': 'f', 'ble': 'm', 'cumulus': 'm',
    'dahlia': 'm', 'democratie': 'f', 'diet': 'f', 'gondole': 'f',
    'heros': 'm', 'inexactitude': 'f', 'niet': 'm', 'offset': 'm',
    'onyx': 'm', 'perruche': 'f', 'petrole': 'm', 'toulonnais': 'epicene',
    'urgentiste': 'epicene', 'vehicule': 'm', 'zigzag': 'm',
    'ébéniste': 'epicene', 'alvéole': 'f', 'anthracite': 'm', 'atoll': 'm',
    'cvs': 'm', 'keuf': 'm', 'mégarde': 'f', 'ontologie': 'f',
    'paname': 'm', 'pharisien': 'm', 'sherry': 'm', 'émigrant': 'epicene',
    'équinoxe': 'm', 'œillet': 'm', 'atour': 'm', 'blender': 'm',
    'cava': 'm', 'cinéphile': 'epicene', 'cotte': 'f', 'doppler': 'm',
    'flanelle': 'f', 'genet': 'm', 'lumen': 'm', 'mamy': 'f',
    'mauricien': 'epicene', 'scale': 'f', 'spitz': 'm', 'unioniste': 'epicene',
    'ventricule': 'm', 'abattant': 'm', 'antimoine': 'm', 'biocarburant': 'm',
    'booker': 'm', 'décibel': 'm', 'espéranto': 'm', 'ethnologue': 'epicene',
    'favela': 'f', 'fortress': 'f', 'irrespect': 'm', 'momentum': 'm',
    'motoneige': 'f', 'octogénaire': 'epicene', 'orb': 'm', 'strie': 'f',
    'telegram': 'm', 'ammoniaque': 'f', 'auvent': 'm', 'bibelot': 'm',
    'bizarrerie': 'f', 'bolchevik': 'm', 'coquelicot': 'm', 'coussinet': 'm',
    'equilibre': 'm', 'escalator': 'm', 'forceps': 'm', 'kana': 'm',
    'nanoparticule': 'f', 'parka': 'f', 'privilege': 'm', 'probléme': 'm',
    'raillerie': 'f', 'turpitude': 'f', 'cheri': 'm', 'criquet': 'm',
    'grand-père': 'm', 'grand-mère': 'f', 'petit-déjeuner': 'm',
    'salle de bain': 'f', 'pique-nique': 'm', "carte d'identité": 'f',
    "homme d'affaires": 'm', "femme d'affaires": 'f', 'tableau noir': 'm',
    'mal de tête': 'm', 'imperméable': 'm', 'week-end': 'm',
    "douleur à l'estomac": 'f', 'douleur dentaire': 'f',
    'brosse à dents': 'f', 'lunettes de soleil': 'f',
    'fauteuil roulant': 'm', 'collants': 'm', "boucle d'oreille": 'f',
    'centre-ville': 'm', 'petit-enfant': 'm', 'petit-fils': 'm',
    'petite-fille': 'f', 'ordinateur portable': 'm', 'sac à main': 'm',
    'écouteurs': 'm', 'cerf-volant': 'm', 'ami de correspondance': 'm',
    'fruits de mer': 'm', 'vaisseau spatial': 'm', 'lumière du soleil': 'f',
    'cuillère à soupe': 'f', 'jour de semaine': 'm',
}
