#!/usr/bin/env python3
"""
generate_audit_html.py — renders audit_vocab.py's data as a single,
self-contained, sortable/filterable HTML table (no server, no external
assets — just open the file). Called automatically by audit_vocab.py, or
run standalone against an existing audit_report.json:

    python3 tools/generate_audit_html.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
IN_JSON = HERE / 'audit_report.json'
OUT_HTML = HERE / 'audit_report.html'

COLUMNS = [
    # (key, label, type) — type controls sort behavior (numeric vs text)
    # and whether it gets the color-coded coverage-cell treatment.
    # 'pct' = high is good (green); 'pct-inverted' = high is bad (red) —
    # concepts% is the generic fallback bucket, so a high share of it means
    # a lot of words have no real topic match, the opposite of "good coverage".
    ('language',            'Language',        'text'),
    ('level',                'Level',           'text'),
    ('words',                'Words',           'num'),
    ('pos_pct',              'POS %',           'pct'),
    ('categories_pct',       'Categories %',    'pct'),
    ('concepts_pct',         'Concepts %',      'pct-inverted'),
    ('examples_pct',         'Examples %',      'pct'),
    ('mnemonics_pct',        'Mnemonics %',     'pct'),
    ('translation_missing',  'Missing Translation', 'num-warn'),
    ('reading_missing',      'Missing Reading', 'num-warn'),
    ('vulgar_only',          'Vulgar-only',     'num'),
    ('distinct_pos',         'Distinct POS',    'num'),
    ('distinct_categories',  'Distinct Categories', 'num'),
]

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Vocab Games — Data Audit Report</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 1100px; margin: 2rem auto; padding: 0 1.5rem;
    color: #1a1a1a; background: #fafafa;
  }}
  h1 {{ font-size: 1.4rem; margin-bottom: 0.2rem; }}
  .subtitle {{ color: #666; font-size: 0.85rem; margin-bottom: 1.2rem; }}
  .controls {{ display: flex; gap: 0.8rem; align-items: center; margin-bottom: 1rem; flex-wrap: wrap; }}
  #filterInput {{
    padding: 0.5rem 0.8rem; border: 1.5px solid #ddd; border-radius: 8px;
    font-size: 0.9rem; width: 220px;
  }}
  .legend {{ font-size: 0.78rem; color: #888; }}
  .legend span {{ display: inline-block; width: 0.7rem; height: 0.7rem; border-radius: 2px; margin: 0 0.25rem 0 0.7rem; vertical-align: middle; }}
  table {{ border-collapse: collapse; width: 100%; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.08); border-radius: 8px; overflow: hidden; }}
  th, td {{ padding: 0.5rem 0.7rem; text-align: right; font-size: 0.85rem; border-bottom: 1px solid #eee; }}
  th:nth-child(1), td:nth-child(1), th:nth-child(2), td:nth-child(2) {{ text-align: left; }}
  th {{
    background: #f0f0f0; cursor: pointer; user-select: none; position: sticky; top: 0;
    font-weight: 700; white-space: nowrap;
  }}
  th:hover {{ background: #e5e5e5; }}
  th.sorted-asc::after {{ content: ' \\2191'; }}
  th.sorted-desc::after {{ content: ' \\2193'; }}
  tr:hover td {{ background: #f7f9ff; }}
  .cov-high {{ background: #e3f6e9; color: #1b7a3d; font-weight: 700; }}
  .cov-mid  {{ background: #fff6db; color: #8a6d00; font-weight: 700; }}
  .cov-low  {{ background: #fde8e8; color: #b3261e; font-weight: 700; }}
  .cov-na   {{ color: #aaa; }}
  .warn     {{ color: #b3261e; font-weight: 700; }}
  .ok       {{ color: #999; }}
  .totals-row td {{ font-weight: 700; background: #f5f5f5; border-top: 2px solid #ddd; }}
  .hidden {{ display: none; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #16171a; color: #eee; }}
    table {{ background: #1e1f22; }}
    th {{ background: #26282c; }}
    th:hover {{ background: #303236; }}
    td {{ border-color: #2c2d31; }}
    tr:hover td {{ background: #24262b; }}
    #filterInput {{ background: #1e1f22; border-color: #3a3b3f; color: #eee; }}
    .cov-high {{ background: #113322; color: #6fdc9b; }}
    .cov-mid  {{ background: #3a2f00; color: #f0c93a; }}
    .cov-low  {{ background: #3a1414; color: #ff9a90; }}
    .totals-row td {{ background: #202124; }}
  }}
</style>
</head>
<body>
<h1>Vocab Games — Data Audit Report</h1>
<p class="subtitle">Generated by tools/audit_vocab.py. Screens structural completeness
(does the field exist) — not a judgment of accuracy (does the field say the
right thing). See TODO.md's "meaning-accuracy audit" entries for that
harder, human-only problem.</p>

<div class="controls">
  <input id="filterInput" type="text" placeholder="Filter by language or level…">
  <span class="legend">Coverage:
    <span style="background:#1b7a3d"></span>&ge;90%
    <span style="background:#8a6d00"></span>50-89%
    <span style="background:#b3261e"></span>&lt;50%
  </span>
</div>

<table id="auditTable">
  <thead><tr id="headerRow"></tr></thead>
  <tbody id="bodyRows"></tbody>
</table>

<script>
const DATA = {data_json};
const COLUMNS = {columns_json};

let sortKey = null;
let sortDir = 1;

function covClass(v) {{
  if (v === null || v === undefined) return 'cov-na';
  if (v >= 90) return 'cov-high';
  if (v >= 50) return 'cov-mid';
  return 'cov-low';
}}
function covClassInverted(v) {{
  if (v === null || v === undefined) return 'cov-na';
  if (v <= 15) return 'cov-high';
  if (v <= 40) return 'cov-mid';
  return 'cov-low';
}}

function cellHTML(col, row) {{
  const v = row[col.key];
  if (col.type === 'pct') {{
    return v === null || v === undefined
      ? '<td class="cov-na">—</td>'
      : `<td class="${{covClass(v)}}">${{v}}%</td>`;
  }}
  if (col.type === 'pct-inverted') {{
    return v === null || v === undefined
      ? '<td class="cov-na">—</td>'
      : `<td class="${{covClassInverted(v)}}">${{v}}%</td>`;
  }}
  if (col.type === 'num-warn') {{
    if (v === null || v === undefined) return '<td class="cov-na">—</td>';
    return `<td class="${{v > 0 ? 'warn' : 'ok'}}">${{v}}</td>`;
  }}
  if (col.type === 'text') return `<td>${{v ?? ''}}</td>`;
  return `<td>${{v ?? '—'}}</td>`;
}}

function render() {{
  const filterVal = document.getElementById('filterInput').value.toLowerCase();
  let rows = DATA.filter(r =>
    !filterVal || r.language.toLowerCase().includes(filterVal) || r.level.toLowerCase().includes(filterVal)
  );

  if (sortKey) {{
    rows = rows.slice().sort((a, b) => {{
      let av = a[sortKey], bv = b[sortKey];
      if (av === null || av === undefined) av = -Infinity;
      if (bv === null || bv === undefined) bv = -Infinity;
      if (typeof av === 'string') return av.localeCompare(bv) * sortDir;
      return (av - bv) * sortDir;
    }});
  }}

  const tbody = document.getElementById('bodyRows');
  tbody.innerHTML = rows.map(r => '<tr>' + COLUMNS.map(c => cellHTML(c, r)).join('') + '</tr>').join('');

  // Totals row across whatever's currently visible (respects the filter)
  if (rows.length) {{
    const totalWords = rows.reduce((s, r) => s + r.words, 0);
    const weightedPct = key => {{
      let num = 0;
      for (const r of rows) if (r[key] !== null) num += (r[key] / 100) * r.words;
      return totalWords ? Math.round((num / totalWords) * 1000) / 10 : null;
    }};
    const totals = {{
      language: `${{rows.length}} rows`, level: '', words: totalWords,
      pos_pct: weightedPct('pos_pct'), categories_pct: weightedPct('categories_pct'),
      concepts_pct: weightedPct('concepts_pct'),
      examples_pct: weightedPct('examples_pct'), mnemonics_pct: weightedPct('mnemonics_pct'),
      translation_missing: rows.reduce((s, r) => s + (r.translation_missing || 0), 0),
      reading_missing: rows.reduce((s, r) => s + (r.reading_missing || 0), 0),
      vulgar_only: rows.reduce((s, r) => s + (r.vulgar_only || 0), 0),
      distinct_pos: '', distinct_categories: '',
    }};
    const tr = document.createElement('tr');
    tr.className = 'totals-row';
    tr.innerHTML = COLUMNS.map(c => cellHTML(c, totals)).join('');
    tbody.appendChild(tr);
  }}
}}

function buildHeader() {{
  const headerRow = document.getElementById('headerRow');
  headerRow.innerHTML = COLUMNS.map(c => `<th data-key="${{c.key}}">${{c.label}}</th>`).join('');
  headerRow.querySelectorAll('th').forEach(th => {{
    th.addEventListener('click', () => {{
      const key = th.dataset.key;
      if (sortKey === key) {{ sortDir *= -1; }} else {{ sortKey = key; sortDir = 1; }}
      headerRow.querySelectorAll('th').forEach(h => h.classList.remove('sorted-asc', 'sorted-desc'));
      th.classList.add(sortDir === 1 ? 'sorted-asc' : 'sorted-desc');
      render();
    }});
  }});
}}

document.getElementById('filterInput').addEventListener('input', render);
buildHeader();
render();
</script>
</body>
</html>
"""


def generate(rows=None):
    if rows is None:
        rows = json.loads(IN_JSON.read_text(encoding='utf-8'))
    columns = [{'key': k, 'label': label, 'type': t} for k, label, t in COLUMNS]
    html = HTML_TEMPLATE.format(
        data_json=json.dumps(rows, ensure_ascii=False),
        columns_json=json.dumps(columns, ensure_ascii=False),
    )
    OUT_HTML.write_text(html, encoding='utf-8')
    return OUT_HTML


if __name__ == '__main__':
    path = generate()
    print(f"Wrote {path}")
