"""
Chinese (zh-en.json) gloss cleanup tooling.

Chinese needed a fundamentally different approach from the other four
languages (DE/ES/FR/JA): a representative sample review found most
long/leading-parenthetical entries are legitimate lexicographic
content (domain tags, grammatical function markers, idiom literal+
figurative glosses, polysemy disambiguation) rather than redundant
clutter, so a bulk "shorten everything" pass would have actively
destroyed real content. Two-phase approach used instead:

Phase 1 (this file's `reposition` function) -- purely structural,
mechanical, safe to apply broadly: move a LEADING parenthetical to
the end of the gloss, matching the "parentheses at the end" rule
agreed for all languages this session (e.g. "(fig.) treasure" ->
"treasure (fig.)"). Handles stacked leading parens recursively
(e.g. "(coll.) (of clothes) to fit nicely" ->
"to fit nicely (coll.) (of clothes)"). Deliberately leaves untouched
any gloss where the parenthetical IS the entire content (pure
grammar/particle markers like "(used before a verb to indicate an
action in progress)" for 在) -- there's no word to reposition around,
and this content is inherently explanatory, not decorative.

Phase 2 -- individual content review, NOT automated. The remaining
"long gloss containing a parenthetical" entries need real per-entry
judgment about whether the content is genuinely reducible (redundant
"e.g." enumeration, hedging) or necessary (idiom explanation, sense
disambiguation) -- there is no reliable heuristic for this
distinction, confirmed by review. Fixes for this phase are applied
via a hand-built dict of specific (old_gloss -> new_gloss) mappings,
built up in batches through manual review, not generated by this
tool. This file only provides phase 1 (the safe structural fix) and
the candidate-listing helper used to find phase-2 candidates for
review.
"""
import json


def reposition_once(gloss):
    s = gloss.strip()
    if not s.startswith('('):
        return gloss, False, 'no-change'
    depth = 0
    close_idx = None
    for i, ch in enumerate(s):
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
            if depth == 0:
                close_idx = i
                break
    if close_idx is None:
        return gloss, False, 'unbalanced-parens'
    paren = s[:close_idx + 1]
    rest = s[close_idx + 1:].strip()
    if not rest:
        return gloss, False, 'pure-marker-no-content'
    rest = rest.lstrip(',;').strip()
    return f"{rest} {paren}", True, 'repositioned'


def reposition(gloss, max_iterations=5):
    """Repeatedly repositions leading parentheticals to the end,
    handling stacked cases. Returns (new_gloss, changed, reason)."""
    current = gloss
    any_change = False
    for _ in range(max_iterations):
        new_gloss, changed, reason = reposition_once(current)
        if not changed:
            return current, any_change, (reason if not any_change else 'repositioned')
        current = new_gloss
        any_change = True
    return current, any_change, 'repositioned'


def find_reposition_fixes(vocab_path='public/vocab/zh-en.json'):
    """Scans the file and returns (headword, gloss_index, old, new)
    tuples for every gloss that can be safely repositioned."""
    d = json.load(open(vocab_path, encoding='utf-8'))
    entries = d['entries']
    idx = {k: i for i, k in enumerate(d['keys'])}
    ei, ti = idx['entry'], idx['translation']
    fixes = []
    for e in entries:
        for i, t in enumerate(e[ti]):
            if t.strip().startswith('('):
                new_t, changed, reason = reposition(t)
                if changed:
                    fixes.append((e[ei], i, t, new_t))
    return fixes


def find_phase2_candidates(vocab_path='public/vocab/zh-en.json', min_len=35):
    """Lists remaining long-gloss-with-parenthetical entries for
    manual phase-2 review (content trimming). Not auto-fixable --
    each needs individual judgment on whether the content is
    reducible or necessary."""
    d = json.load(open(vocab_path, encoding='utf-8'))
    entries = d['entries']
    idx = {k: i for i, k in enumerate(d['keys'])}
    ei, ti, pi = idx['entry'], idx['translation'], idx['pos']
    candidates = []
    for e in entries:
        for t in e[ti]:
            if '(' in t and len(t) > min_len:
                candidates.append((e[ei], t, e[pi]))
    return candidates


if __name__ == '__main__':
    fixes = find_reposition_fixes()
    print(f"Phase 1 (structural reposition) candidates: {len(fixes)}")
    candidates = find_phase2_candidates()
    print(f"Phase 2 (content review) candidates remaining: {len(candidates)}")
